/* ==========================================================================
   EightyTwentyVentures — Magic Link Verifier
   Validates the HMAC token generated by send-token.js.
   Stateless: no database, no storage. Token carries its own timestamp.

   Environment variables required:
     TOKEN_SECRET  — must match the value used in send-token.js
   ========================================================================== */

const crypto = require('crypto');

const EXPIRY_MS = 30 * 60 * 1000;   // 30 minutes — must match send-token.js

exports.handler = async function (event) {
  if (event.httpMethod !== 'POST') {
    return { statusCode: 405, body: 'Method Not Allowed' };
  }

  /* ── Parse body ─────────────────────────────────────────────── */
  let email, token;
  try {
    const body = JSON.parse(event.body || '{}');
    email = (body.email || '').trim().toLowerCase();
    token = (body.token || '').trim();
  } catch (e) {
    return { statusCode: 400, body: respond(false, 'Invalid JSON') };
  }

  if (!email || !token) {
    return { statusCode: 400, body: respond(false, 'Missing email or token') };
  }

  /* ── Config check ───────────────────────────────────────────── */
  const secret = process.env.TOKEN_SECRET;
  if (!secret) {
    console.error('TOKEN_SECRET is not set');
    return { statusCode: 500, body: respond(false, 'Server configuration error') };
  }

  /* ── Structural validation ──────────────────────────────────── */
  const parts = token.split('.');
  if (parts.length !== 2) {
    return { statusCode: 200, body: respond(false, 'Malformed token') };
  }

  const [tsStr, hmac] = parts;
  const ts = parseInt(tsStr, 10);

  if (isNaN(ts)) {
    return { statusCode: 200, body: respond(false, 'Invalid token') };
  }

  /* ── Expiry check ───────────────────────────────────────────── */
  if (Date.now() - ts > EXPIRY_MS) {
    return {
      statusCode: 200,
      body: respond(false, 'Link expired. Request a new one from the homepage.')
    };
  }

  /* ── HMAC verification (constant-time) ──────────────────────── */
  const payload  = `${email}|${tsStr}`;
  const expected = crypto.createHmac('sha256', secret).update(payload).digest('hex');

  let valid = false;
  try {
    if (
      hmac.length === expected.length &&
      /^[0-9a-f]+$/.test(hmac)
    ) {
      const a = Buffer.from(hmac,     'hex');
      const b = Buffer.from(expected, 'hex');
      if (a.length === b.length) {
        valid = crypto.timingSafeEqual(a, b);
      }
    }
  } catch (e) {
    valid = false;
  }

  return {
    statusCode: 200,
    headers: { 'Content-Type': 'application/json' },
    body: valid
      ? respond(true)
      : respond(false, 'Invalid link. Please request a new one.')
  };
};

function respond (valid, error) {
  const payload = { valid };
  if (error) payload.error = error;
  return JSON.stringify(payload);
}
